CD OBJ
IF "%1"=="NODEBUG" MAKE REL=NODEBUG MAKEFILE
IF NOT "%1"=="NODEBUG" MAKE REL=DEBUG MAKEFILE
IF ERRORLEVEL 1 GOTO EXIT
COPY COMMAND.COM A:
CD ..
IF "%2"=="" GOTO EXIT
CD ..\UTIL
MK %1 %2
:EXIT
