DEL BOOT\*.COM
DEL BOOT\*.MAP
DEL DEV\*.COM
DEL DEV\*.MAP
DEL DOS\*.OBJ
DEL DOS\*.COM
DEL DOS\*.MAP
DEL UTIL\*.COM
DEL UTIL\*.MAP
CD BOOT
REM Use MK NODEBUG to create a non-debug release
IF "%1"=="" MK DEBUG ALL
IF NOT "%1"=="" MK %1 ALL
