ECHO OFF
IF EXIST OS\BOOT\OBJ\*.COM DEL OS\BOOT\OBJ\*.COM
IF EXIST OS\BOOT\OBJ\*.MAP DEL OS\BOOT\OBJ\*.MAP
IF EXIST OS\DEV\OBJ\*.COM DEL OS\DEV\OBJ\*.COM
IF EXIST OS\DEV\OBJ\*.MAP DEL OS\DEV\OBJ\*.MAP
IF EXIST OS\DOS\OBJ\*.OBJ DEL OS\DOS\OBJ\*.OBJ
IF EXIST OS\DOS\OBJ\*.COM DEL OS\DOS\OBJ\*.COM
IF EXIST OS\DOS\OBJ\*.MAP DEL OS\DOS\OBJ\*.MAP
IF EXIST OS\CMD\OBJ\*.OBJ DEL OS\CMD\OBJ\*.OBJ
IF EXIST OS\CMD\OBJ\*.COM DEL OS\CMD\OBJ\*.COM
IF EXIST OS\CMD\OBJ\*.MAP DEL OS\CMD\OBJ\*.MAP
IF EXIST TESTS\OBJ\*.COM DEL TESTS\OBJ\*.COM
IF EXIST TESTS\OBJ\*.EXE DEL TESTS\OBJ\*.EXE
IF EXIST TESTS\OBJ\*.MAP DEL TESTS\OBJ\*.MAP
MK %1
