IF "%1"=="FINAL" MAKE REL=FINAL MAKEFILE
IF NOT "%1"=="FINAL" MAKE REL=DEBUG MAKEFILE
IF ERRORLEVEL 1 GOTO EXIT
CD OBJ
WBOOT BOOT.COM BOOT2.COM
CD ..
IF ERRORLEVEL 1 GOTO EXIT
IF "%2"=="" GOTO EXIT
CD ..\DEV
MK %1 %2
:EXIT
