;
; BASIC-DOS Library Console Functions
;
; @author Jeff Parsons <Jeff@pcjs.org>
; @copyright (c) 2020-2026 Jeff Parsons
; @license MIT <https://basicdos.com/LICENSE.txt>
;
; This file is part of PCjs, a computer emulation software project at pcjs.org
;
	include	cmd.inc

CODE    SEGMENT

	EXTNEAR	<parseDOS,releaseStr,strIllegal>
	EXTSTR	<STR_ON,STR_OFF>

        ASSUME  CS:CODE, DS:NOTHING, ES:NOTHING, SS:CODE

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; callDOS
;
; Process DOS command generated by genDOS.
;
; Inputs:
;	[pHandler] -> handler offset
;	[idKeyword] -> keyword ID
;	[cbCmdLine] == length of command line
;	[pCmdLine] -> seg:off of command line
;
; Outputs:
;	None
;
; Modifies:
;	AX, BX, CX, DX, SI, DI, ES
;
DEFPROC	callDOS,FAR
	ARGVAR	pHandler,word
	ARGVAR	idKeyword,word
	ARGVAR	cbCmdLine,word
	ARGVAR	pCmdLine,dword
	ENTER
	push	ds
	push	[idKeyword]
	mov	dx,[pHandler]
	mov	cx,[cbCmdLine]		; CX = length
	lds	si,[pCmdLine]		; DS:SI -> command
;
; The line at DS:SI may be sitting in LINEBUF, which is large enough to
; accommodate lines up to 255 characters.  However, DOS commands (at least
; external commands) are more constrained; for example, command tails
; are limited to 127 characters (see PSP_CMDTAIL).
;
; Since cmdFile (the function that processes external commands) also wants
; to use LINEBUF, we're going to copy as much as we can to space available
; in the PSP; but instead of starting at PSP_CMDTAIL, we'll start at PSP_FCB2,
; which provides enough room for a filename plus a command tail.
;
	push	ss
	pop	es
	mov	di,PSP_FCB2		; ES:DI -> PSP_FCB2
	cmp	cx,size PSP - PSP_FCB2 - 1
	jbe	cd1
	mov	cx,size PSP - PSP_FCB2 - 1
cd1:	push	cx
	push	es
	push	di
	rep	movsb
	mov	al,0			; null-terminate for good measure
	stosb
	pop	si
	pop	ds			; DS:SI -> PSP_FCB2
	pop	cx
	mov	bx,es:[PSP_HEAP]
	lea	di,[bx].TOKENBUF	; ES:DI -> TOKENBUF
	mov	[di].TOK_MAX,(size TOK_DATA) / (size TOKLET)
	DOSUTIL	TOKEN1
	ASSERT	NC
	pop	ax			; AX = keyword ID, if any
	mov	cl,[di].TOK_DATA[0].TOKLET_LEN
	call	parseDOS		; CX = length of first token only
	pop	ds
	LEAVE
	RETURN
ENDPROC	callDOS

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; clearScreen
;
; Used by "CLS".
;
; Inputs:
;	None
;
; Outputs:
;	None
;
; Modifies:
;	AX, BX, CX, DX
;
DEFPROC	clearScreen,FAR
	sub	cx,cx
	mov	al,IOCTL_SCROLL
	call	ioctlCon
	ret
ENDPROC	clearScreen

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; getArgs
;
; Removes the numeric arguments that genArgs pushed for a runtime function
; (ie, N arguments followed by N), and returns the first three in registers.
; Every argument must be 0-255, or -1 if it was omitted (which is also the
; value of any argument beyond N); otherwise, an "Illegal function call"
; error occurs.
;
; Call this first thing in the runtime function, so that the stack contains
; only our return address, the function's (far) return address, and the
; arguments.
;
; Inputs:
;	N arguments and N pushed on stack (see genArgs)
;
; Outputs:
;	AX = 1st argument, DX = 2nd argument, CX = 3rd argument
;	Stack cleaned (only the function's return address remains)
;
; Modifies:
;	AX, CX, DX, SI, DI
;
DEFPROC	getArgs
	push	bp
	mov	bp,sp
	mov	si,[bp+8]		; SI = N
	mov	ax,-1
	cwd
	mov	cx,ax
;
; Arguments are on the stack in reverse order, so as we load each one, we
; shift the previous ones down, ending with the 1st argument in AX.
;
ga1:	dec	si
	jl	ga8
	mov	cx,dx
	mov	dx,ax
	add	bp,4
	mov	ax,[bp+6]
	mov	di,[bp+8]		; DI:AX = next argument
	add	ax,1
	adc	di,0			; DI:AX = argument + 1
	jnz	ga9			; argument must be -1 to 255
	cmp	ax,256
	ja	ga9
	dec	ax
	jmp	ga1
;
; Move both return addresses above the arguments (whose last word is now at
; BP+8), restore BP, and point SP at the return addresses.  Every move is to
; a higher address, so no source is overwritten before it's read, and SP is
; updated last, since anything below SP can be overwritten by interrupts.
;
ga8:	mov	si,sp			; SS:SI -> saved BP
	mov	di,ss:[si+6]
	mov	[bp+8],di
	mov	di,ss:[si+4]
	mov	[bp+6],di		; the function's return address
	mov	di,ss:[si+2]
	mov	[bp+4],di		; our return address
	mov	si,ss:[si]
	lea	sp,[bp+4]
	mov	bp,si			; restore BP
	ret
ga9:	jmp	strIllegal
ENDPROC	getArgs

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; getMode
;
; Inputs:
;	None
;
; Outputs:
;	If carry clear (ie, STDOUT supports video modes):
;	BH = current video mode (or 3 if it's 7, the MDA's 80-column mode)
;	BL = index of BH in MODE_TBL (see setScreen)
;
; Modifies:
;	AX, BX, DX
;
DEFPROC	getMode
	mov	al,IOCTL_GETMODE
	call	ioctlCon		; DL = video mode
	jc	gm9
	cmp	dl,7			; MDA mode?
	jne	gm1			; no
	mov	dl,3			; yes, treat it like mode 3
gm1:	mov	bl,dl
	and	bx,7
	mov	bl,cs:MODE_INFO[bx]
	mov	bh,dl
gm9:	ret
ENDPROC	getMode

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; saveMode
;
; Called before a BAS program runs, to save the video mode, so that it can be
; restored when the program ends (see restoreMode).  Only the outermost BAS
; program saves the mode (a BAS program run by another BAS program does not).
;
; The mode is saved in GFX_DATA+7 (as mode + 1, or 0 if none is saved).
;
; Inputs:
;	None
;
; Outputs:
;	AX = 1 if the mode was saved, 0 if not
;
; Modifies:
;	AX
;
DEFPROC	saveMode
	push	bx
	push	dx
	mov	bx,ss:[PSP_HEAP]
	sub	ax,ax
	cmp	byte ptr ss:[bx].GFX_DATA+7,al	; already saved?
	jne	svm9				; yes
	mov	al,IOCTL_GETMODE
	call	ioctlCon		; DL = video mode
	mov	ax,0
	jc	svm9			; STDOUT doesn't support video modes
	inc	dx
	mov	bx,ss:[PSP_HEAP]
	mov	byte ptr ss:[bx].GFX_DATA+7,dl
	inc	ax
svm9:	pop	dx
	pop	bx
	ret
ENDPROC	saveMode

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; restoreMode
;
; Called when a BAS program ends (normally, or when it's aborted; see ctrlc),
; to restore the video mode saved by saveMode, if the program changed it
; (eg, with SCREEN or WIDTH).
;
; Inputs:
;	None
;
; Outputs:
;	None
;
; Modifies:
;	None
;
DEFPROC	restoreMode
	push	ax
	push	bx
	push	cx
	push	dx
	mov	bx,ss:[PSP_HEAP]
	mov	cl,0
	xchg	cl,byte ptr ss:[bx].GFX_DATA+7
	dec	cl			; CL = saved mode
	js	rsm9			; there isn't one
	push	cx
	mov	al,IOCTL_GETMODE
	call	ioctlCon		; DL = video mode
	pop	cx
	jc	rsm9
	cmp	dl,cl			; did the mode change?
	je	rsm9			; no
	mov	al,IOCTL_SETMODE
	call	ioctlCon		; yes, so restore it
	mov	bx,ss:[PSP_HEAP]
	mov	byte ptr ss:[bx].GFX_DATA+6,0	; (see gfxInit)
rsm9:	pop	dx
	pop	cx
	pop	bx
	pop	ax
	ret
ENDPROC	restoreMode

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; ioctlCon
;
; Inputs:
;	AL = IOCTL code (eg, IOCTL_GETPOS)
;	CX, DX = IOCTL inputs, if any
;
; Outputs:
;	Same as DOS_HDL_IOCTL (eg, DX = result) for STDOUT
;
; Modifies:
;	AX, BX, DX
;
DEFPROC	ioctlCon
	mov	ah,DOS_HDL_IOCTL
	mov	bx,STDOUT
	int	21h
	ret
ENDPROC	ioctlCon

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; printArgs
;
; Used by "PRINT [args]"
;
; Since expressions are evaluated left-to-right, their results are pushed
; left-to-right as well.  And since the number of parameters is variable, we
; walk the stacked parameters back to the beginning, pushing the offset of
; each as we go, and then popping and printing our way back to the end again.
;
; Inputs:
;	N pairs of variable types/values pushed on stack
;
; Outputs:
;	None
;
; Modifies:
;	AX, BX, CX, DX, DI, ES
;
DEFPROC	printArgs,FAR
	push	bp			; preserve BP (see genEnd)
	mov	bp,sp
	add	bp,6
	sub	bx,bx
	push	bx			; push end-of-args marker
	mov	bx,bp

pa1:	mov	al,[bp]			; AL = arg type
	test	al,al
	jz	pa3
pa2:	push	bp
	lea	bp,[bp+2]
	cmp	al,VAR_LONG		; if AL < VAR_LONG that's trouble
	jb	pa1
;
; Every value is 4 bytes: a VAR_LONG, or a far pointer to a VAR_STR or
; VAR_DOUBLE (since doubles, like strings, are always passed by reference).
; If AL > VAR_DOUBLE that's trouble, because we don't know how to print
; VAR_FUNC or VAR_ARRAY variables.
;
	ASSERT	BE,<cmp al,VAR_DOUBLE>
	lea	bp,[bp+4]
	jmp	pa1

pa3:	lea	bp,[bp+2]
	sub	bp,bx
	mov	bx,bp			; BX = # bytes to clean off stack
;
; After printing any value, AL must be non-zero, so that we end on a new line
; (unless a separator follows the value).
;
pa4v:	mov	al,VAR_NEWLINE

pa4:	pop	bp
	test	bp,bp			; end-of-args marker?
	jz	pa8			; yes

	mov	al,[bp]			; AL = arg type
	cmp	al,VAR_SEMI
	je	pa4a
	cmp	al,VAR_COMMA
	jne	pa5
	PRINTF	<CHR_TAB>
pa4a:	mov	al,VAR_NONE		; if we end on this, there's no NEWLINE
	jmp	pa4
;
; Check for numeric types first: VAR_LONG, and then VAR_DOUBLE (whose far
; pointer we simply pass along to the %f formatter).
;
pa5:	cmp	al,VAR_LONG
	jne	pa6
	mov	ax,[bp+2]
	mov	dx,[bp+4]
;
; As the itoa code in sprintf.asm explains, we use the '#' (hash) flag with
; decimal output to signify that a space should precede positive values.
;
	PRINTF	<"%#ld ">,ax,dx		; DX:AX = 32-bit value
	jmp	pa4v
;
; VAR_DOUBLE is next, whose far pointer we simply pass to the %f formatter.
;
pa6:	cmp	al,VAR_DOUBLE
	jne	pa6a
	mov	ax,[bp+2]
	mov	dx,[bp+4]
	PRINTF	<"%#f ">,ax,dx		; DX:AX -> double
	jmp	pa4v
;
; Last but not least, VAR_STR, which we must release after printing, since
; it may be a temporary string (eg, the result of a string operation).
;
pa6a:	cmp	al,VAR_STR
	jne	pa4			; not a string type

	push	ds			; save DS
	lds	si,[bp+2]		; DS:SI = string pointer
	mov	cx,ds
	jcxz	pa7a			; nothing to do for null pointer
	call	writeStr		; write the string at DS:SI to STDOUT
	les	di,[bp+2]
	call	releaseStr

pa7a:	pop	ds			; restore DS
	jmp	pa4v
;
; We've reached the end of arguments, wrap it up.
;
pa8:	test	al,al			; unless AL is zero
	jz	pa9			; we want to end on a new line
	PRINTF	<13,10>

pa9:	pop	bp			; restore BP
	pop	dx			; remove return address
	pop	cx
	add	sp,bx			; clean the stack
	push	cx			; restore the return address
	push	dx
	ret
ENDPROC	printArgs

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; printEcho
;
; Inputs:
;	None
;
; Outputs:
;	None
;
; Modifies:
;	AX, BX
;
DEFPROC	printEcho,FAR
	mov	bx,ss:[PSP_HEAP]
	test	ss:[bx].CMD_FLAGS,CMD_NOECHO
	mov	bx,offset STR_ON
	jz	pe1
	mov	bx,offset STR_OFF
pe1:	PRINTF	<"ECHO is %ls",13,10>,bx,cs
	ret
ENDPROC	printEcho

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; printLine
;
; Inputs:
;	Pointer to length-prefixed string pushed on stack
;
; Outputs:
;	None
;
; Modifies:
;	AX, BX, CX, DX, SI
;
DEFPROC	printLine,FAR
	mov	bx,ss:[PSP_HEAP]
	test	ss:[bx].CMD_FLAGS,CMD_NOECHO
	jz	pl1
	ret	4
pl1:	PRINTF	<13,10>			; fall into printStr
ENDPROC	printLine

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; printStr
;
; Inputs:
;	Pointer to length-prefixed string pushed on stack
;
; Outputs:
;	None
;
; Modifies:
;	AX, BX, CX, DX, SI
;
DEFPROC	printStr,FAR
	ARGVAR	pStr,dword
	ENTER
	push	ds
	lds	si,[pStr]		; DS:SI -> length-prefixed string
	call	writeStrCRLF
	pop	ds
	LEAVE
	RETURN
ENDPROC	printStr

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; writeStr
;
; Inputs:
;	DS:SI -> length-prefixed string
;
; Outputs:
;	AX = # bytes printed
;	SI updated to end of string
;
; Modifies:
;	AX, CX, DX, SI
;
DEFPROC	writeStr
	push	bx
	lodsb				; AL = string length (255 max)
	mov	ah,0
	xchg	cx,ax			; CX = length
	mov	dx,si			; DS:DX -> data
	add	si,cx
	mov	bx,STDOUT
	mov	ah,DOS_HDL_WRITE
	int	21h
	pop	bx
	ret
ENDPROC	writeStr

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; writeStrCRLF
;
; Inputs:
;	DS:SI -> length-prefixed string
;
; Outputs:
;	AX = # bytes written
;	SI updated to end of string
;
; Modifies:
;	AX, CX, DX, SI
;
DEFPROC	writeStrCRLF
	call	writeStr
	PRINTF	<13,10>
	ret
ENDPROC	writeStrCRLF

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; setColor
;
; Used by "COLOR [fgnd][,[bgnd][,border]]"
;
; As in MSBASIC, a foreground of 16-31 is a blinking foreground of 0-15.
; In graphics modes, the CON driver treats fgnd as the background color and
; bgnd as the palette.
;
; Inputs:
;	N numeric expressions pushed on stack (only 1st 3 are processed)
;
; Outputs:
;	None
;
; Modifies:
;	AX, BX, CX, DX, SI, DI
;
DEFPROC	setColor,FAR
	call	getArgs			; AX = fgnd, DX = bgnd, CX = border
	push	ax
	push	dx
	push	cx
	mov	al,IOCTL_GETCOLOR
	call	ioctlCon		; DX = current colors
	jnc	sc1
	mov	dx,0707h		; use defaults if unsupported
sc1:	pop	ax			; AX = border
	test	ax,ax			; omitted?
	js	sc2			; yes
	mov	dh,al
sc2:	pop	ax			; AX = bgnd
	test	ax,ax
	js	sc3
	mov	cl,4
	shl	al,cl
	and	dl,0Fh
	or	dl,al
sc3:	pop	ax			; AX = fgnd
	test	ax,ax
	js	sc5
	and	dl,0F0h
	test	al,10h			; blinking foreground?
	jz	sc4			; no
	or	dl,80h			; yes
sc4:	and	al,0Fh
	or	dl,al
sc5:	mov	cx,dx			; CX = new colors
	mov	al,IOCTL_SETCOLOR
	call	ioctlCon
	ret
ENDPROC	setColor

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; setPos
;
; Used by "LOCATE [row][,[col][,cursor]]" (as with COLOR, any additional
; arguments, such as the cursor's scan lines, are ignored).  Row and col are
; 1-based, and cursor is 0 to hide the cursor (until the next input) or 1 to
; show it.  Nothing happens if STDOUT doesn't support cursor positioning.
;
; Inputs:
;	N numeric expressions pushed on stack (only 1st 3 are processed)
;
; Outputs:
;	None
;
; Modifies:
;	AX, BX, CX, DX, SI, DI
;
DEFPROC	setPos,FAR
	call	getArgs			; AX = row, DX = col, CX = cursor
	push	cx
	push	ax
	push	dx
	mov	al,IOCTL_GETPOS
	call	ioctlCon		; DL = col, DH = row (zero-based)
	pop	ax			; AX = col
	pop	cx			; CX = row
	pop	bx			; BX = cursor
	jc	sp9			; not supported
	test	ax,ax			; col omitted?
	js	sp1			; yes
	dec	ax			; make it zero-based
	js	sp8			; col 0 is illegal
	mov	dl,al
sp1:	xchg	ax,cx			; AX = row
	test	ax,ax
	js	sp2
	dec	ax
	js	sp8
	mov	dh,al
sp2:	mov	cx,dx			; CX = new position
	mov	dx,bx			; DL = cursor
	mov	al,IOCTL_SETPOS
	call	ioctlCon
	jc	sp8			; position is outside the console
sp9:	ret
sp8:	jmp	strIllegal
ENDPROC	setPos

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; setScreen
;
; Used by "SCREEN [mode][,burst]" (any additional arguments are ignored).
;
; Mode is 0 for text, 1 for 320x200 graphics, or 2 for 640x200 graphics, and
; burst enables color in mode 0 if it's non-zero, and disables it in mode 1.
; SCREEN 0 keeps the current width (40 columns after SCREEN 1, 80 after
; SCREEN 2), and omitted values keep their current settings.  Nothing happens
; if STDOUT doesn't support video modes, or if the video mode is unchanged.
;
; Every combination of these settings is an index into MODE_TBL:
;
;	index = mode * 4 + 2 (if color is disabled) + 1 (if 80 columns)
;
; and MODE_INFO maps video modes 0-7 back to their indexes.
;
; Inputs:
;	N numeric expressions pushed on stack (only 1st 2 are processed)
;
; Outputs:
;	None
;
; Modifies:
;	AX, BX, CX, DX, SI, DI
;
DEFPROC	setScreen,FAR
	call	getArgs			; AX = mode, DX = burst
	push	dx
	push	ax
	call	getMode			; BL = index, BH = video mode
	pop	ax
	pop	dx
	jc	ss9			; not supported
	test	ax,ax			; mode omitted?
	js	ss2			; yes
	cmp	al,2
	ja	ss8
	and	bl,3			; keep the color and width bits
	shl	al,1
	shl	al,1
	or	bl,al
	cmp	al,4			; SCREEN 1?
	jne	ss2			; no
	and	bl,NOT 1		; yes, so it's 40 columns
ss2:	test	dx,dx			; burst omitted?
	js	ss4			; yes
	cmp	dx,1			; carry set if burst is zero
	sbb	al,al			; AL = -1 if burst is zero
	test	bl,0Ch			; graphics mode?
	jz	ss3			; no
	not	al			; yes, so burst has the opposite effect
ss3:	and	al,2			; AL = 2 if color is disabled
	and	bl,NOT 2
	or	bl,al

ss4:	mov	cl,bh			; CL = current video mode
	mov	bh,0
	mov	al,cs:MODE_TBL[bx]	; AL = new video mode
	cmp	al,cl			; any change?
	je	ss9			; no
	xchg	cx,ax			; CL = new video mode
	mov	al,IOCTL_SETMODE
	call	ioctlCon
	jc	ss8			; the adapter doesn't support the mode
	mov	bx,ss:[PSP_HEAP]
	mov	byte ptr ss:[bx].GFX_DATA+6,0	; see gfxInit
ss9:	ret
ss8:	jmp	strIllegal
ENDPROC	setScreen

MODE_TBL	db	1,3,0,2,4,6,5,6,6,6,6,6
MODE_INFO	db	2,0,3,1,4,6,9,1

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; setWidth
;
; Used by "WIDTH 40" and "WIDTH 80".  Like MSBASIC, WIDTH in a graphics mode
; selects SCREEN 1 (40) or SCREEN 2 (80); see setScreen for details.
;
; Inputs:
;	N numeric expressions pushed on stack (only the 1st is processed)
;
; Outputs:
;	None
;
; Modifies:
;	AX, BX, CX, DX, SI, DI
;
DEFPROC	setWidth,FAR
	call	getArgs			; AX = width
	push	ax
	call	getMode			; BL = index, BH = video mode
	pop	ax
	jc	ss9			; not supported
	and	bl,NOT 1		; presume 40 columns
	cmp	ax,40
	je	sw1
	cmp	ax,80
	jne	ss8
	inc	bx			; 80 columns
sw1:	test	bl,0Ch			; graphics mode?
	jz	ss4			; no
	and	bl,3			; yes, keep the color and width bits
	or	bl,4			; for SCREEN 1 (MODE_TBL maps 80 to 2)
	jmp	ss4
ENDPROC	setWidth

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; setFlags
;
; If AL contains a single bit, that bit will be set in CMD_FLAGS;
; otherwise, AL will be used as a mask to clear bit(s) in CMD_FLAGS.
;
; Inputs:
;	AL = bit to set (eg, CMD_NOECHO) or clear (eg, NOT CMD_ECHO)
;
; Outputs:
;	None
;
; Modifies:
;	AX, BX, CX, DX, SI
;
DEFPROC	setFlags,FAR
	mov	bx,ss:[PSP_HEAP]
	mov	ah,al
	dec	ah			; AH = flags - 1
	and	ah,al			; if (flags - 1) AND flags is zero
	jz	sf1			; then AL contains a single bit to set
	and	ss:[bx].CMD_FLAGS,al
	xor	al,al
sf1:	or	ss:[bx].CMD_FLAGS,al
	ret
ENDPROC	setFlags

CODE	ENDS

	end
