IF "%1"=="NODEBUG" MAKE REL=NODEBUG MAKEFILE
IF NOT "%1"=="NODEBUG" MAKE REL=DEBUG MAKEFILE
IF ERRORLEVEL 1 GOTO EXIT
COPY IBMDOS.COM A:
ECHO MEMSIZE=64>A:CONFIG.SYS
ECHO FILES=20>>A:CONFIG.SYS
ECHO CONSOLE=CON:40,25,0,0>>A:CONFIG.SYS
ECHO SHELL=COMMAND.COM>>A:CONFIG.SYS
ECHO CONSOLE=CON:40,25,40,0>>A:CONFIG.SYS
ECHO SHELL=COMMAND.COM PRIMES.COM>>A:CONFIG.SYS
IF "%2"=="" GOTO EXIT
CD ..\UTIL
MK %1 %2
:EXIT
