IF NOT EXIST OBJ\NUL MKDIR OBJ
IF "%1"=="FINAL" MAKE REL=FINAL MAKEFILE
IF NOT "%1"=="FINAL" MAKE REL=DEBUG MAKEFILE
IF ERRORLEVEL 1 GOTO EXIT
COPY PRIMES.BA* ..\CONFIGS\200A > NUL
COPY OBJ\*.EXE ..\CONFIGS\200A > NUL
COPY OBJ\*.COM ..\CONFIGS\200A > NUL
COPY BD*.BAT ..\CONFIGS\200A > NUL
IF "%2"=="" GOTO EXIT
CD ..\MSB
MK %1 %2
:EXIT
