ECHO OFF
IF NOT EXIST OBJ\NUL MKDIR OBJ
IF "%1"=="FINAL" MAKE REL=FINAL MAKEFILE
IF NOT "%1"=="FINAL" MAKE REL=DEBUG MAKEFILE
IF ERRORLEVEL 1 GOTO EXIT
COPY PRIMES\PRIMES.BA* ..\CONFIGS\200B > NUL
COPY BIN\*.EXE ..\CONFIGS\200B > NUL
COPY BIN\*.COM ..\CONFIGS\200B > NUL
COPY MISC\BD*.BAT ..\CONFIGS\200B > NUL
IF "%2"=="" GOTO EXIT
CD ..\MSB
MK %1 %2
:EXIT
