DEL A:*.COM
DEL A:*.SYS
MAKE MAKEFILE
IF ERRORLEVEL 1 GOTO END
COPY DEV\IBMBIO.COM A:
COPY DOS\IBMDOS.COM A:
COPY UTIL\COMMAND.COM A:
COPY UTIL\PRIMES.COM A:
COPY UTIL\TESTS.COM A:
ECHO FILES=20>A:CONFIG.SYS
ECHO CONSOLE=CON:40,25,0,0>>A:CONFIG.SYS
ECHO SHELL=COMMAND.COM>>A:CONFIG.SYS
ECHO CONSOLE=CON:40,25,40,0>>A:CONFIG.SYS
ECHO SHELL=PRIMES.COM>>A:CONFIG.SYS
:END
