IF "%1"=="FINAL" MAKE REL=FINAL MAKEFILE
IF NOT "%1"=="FINAL" MAKE REL=DEBUG MAKEFILE
IF ERRORLEVEL 1 GOTO EXIT
REM COPY OBJ\*.COM A:
REM COPY *.TXT A:
IF "%2"=="" GOTO EXIT
CD ..\..\TEST
MK %1 %2
:EXIT
