MKDIR OBJ
IF "%1"=="FINAL" MAKE REL=FINAL MAKEFILE
IF NOT "%1"=="FINAL" MAKE REL=DEBUG MAKEFILE
IF ERRORLEVEL 1 GOTO EXIT
CD OBJ
WBOOT BOOT1.COM BOOT2.COM /N
CD ..
IF ERRORLEVEL 1 GOTO EXIT
IF "%2"=="" GOTO EXIT
CD ..\DEV
MK %1 %2
:EXIT
