IF "%1"=="FINAL" MAKE REL=FINAL MAKEFILE
IF NOT "%1"=="FINAL" MAKE REL=DEBUG MAKEFILE
IF ERRORLEVEL 1 GOTO EXIT
COPY OBJ\PRIMES.EXE A:
COPY OBJ\SLEEP.COM A:
COPY OBJ\TESTDOS.COM A:
IF "%2"=="" GOTO EXIT
CD ..\MSB
MK %1 %2
:EXIT
