IF "%1"=="FINAL" MAKE REL=FINAL MAKEFILE
IF NOT "%1"=="FINAL" MAKE REL=DEBUG MAKEFILE
IF ERRORLEVEL 1 GOTO EXIT
COPY PRIMES.BA* ..\CONF\200A
COPY OBJ\*.EXE ..\CONF\200A
COPY OBJ\*.COM ..\CONF\200A
COPY BD*.BAT ..\CONF\200A
IF "%2"=="" GOTO EXIT
CD ..\MSB
MK %1 %2
:EXIT
