IF "%1"=="NODEBUG" MAKE REL=NODEBUG MAKEFILE
IF NOT "%1"=="NODEBUG" MAKE REL=DEBUG MAKEFILE
IF ERRORLEVEL 1 GOTO EXIT
COPY COMMAND.COM A:
COPY PRIMES.EXE A:
COPY SLEEP.COM A:
IF "%2"=="" GOTO EXIT
CD ..
:EXIT
