IF "%1"=="NODEBUG" MAKE REL=NODEBUG MAKEFILE
IF NOT "%1"=="NODEBUG" MAKE REL=DEBUG MAKEFILE
IF ERRORLEVEL 1 GOTO EXIT
ECHO MEMSIZE=64>A:CONFIG.SYS
ECHO FILES=20>>A:CONFIG.SYS
ECHO CONSOLE=CON:40,25,0,0>>A:CONFIG.SYS
ECHO SHELL=COMMAND.COM>>A:CONFIG.SYS
ECHO CONSOLE=CON:40,25,40,0>>A:CONFIG.SYS
ECHO SHELL=COMMAND.COM PRIMES.EXE>>A:CONFIG.SYS
COPY COMMAND.COM A:
COPY PRIMES.EXE A:
COPY SLEEP.COM A:
IF "%2"=="" GOTO EXIT
CD ..
:EXIT
