CD OBJ
IF "%1"=="NODEBUG" MAKE REL=NODEBUG MAKEFILE
IF NOT "%1"=="NODEBUG" MAKE REL=DEBUG MAKEFILE
IF ERRORLEVEL 1 GOTO EXIT
COPY PRIMES.EXE A:
COPY SLEEP.COM A:
COPY TESTS.COM A:
CD ..
IF "%2"=="" GOTO EXIT
CD ..\GWB
MK %1 %2
:EXIT
